export interface DeviceTechnicalSnapshot {
  readonly appBuildId: string;
  readonly experimentProfileId: string;
  readonly requestedCameraWidth: number;
  readonly requestedCameraHeight: number;
  readonly requestedFrameRateIdeal: number;
  readonly requestedFrameRateMin: number;
  readonly requestedDelegate: string;
  readonly requestedModelId: string;
  readonly pageUrl: string;
  readonly userAgent: string;
  readonly viewport: string;
  readonly devicePixelRatio: number;
  readonly actualCameraWidth: number | null;
  readonly actualCameraHeight: number | null;
  readonly actualCameraFrameRate: number | null;
  readonly actualFacingMode: string | null;
  readonly cameraFps: number | null;
  readonly trackingHz: number | null;
  readonly inferenceP50Ms: number | null;
  readonly inferenceP95Ms: number | null;
  readonly frameAgeP95Ms: number | null;
  readonly oneHandCoverage: number | null;
  readonly twoHandCoverage: number | null;
  readonly frameSource: string | null;
  readonly delegate: string | null;
  readonly packageId: string | null;
  readonly modelId: string | null;
  readonly capturedFrames: number | null;
  readonly completedFrames: number | null;
  readonly replacedFrames: number | null;
  readonly erroredFrames: number | null;
  readonly inFlightFrames: number | null;
  readonly pendingFrames: number | null;
  readonly trackingError: string | null;
}
